name: Workflow CI SML Jose Manurung

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-ml-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Basic Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn matplotlib seaborn

    - name: Run Pipeline Simulation
      run: |
        echo "Menjalankan otomatisasi pipeline..."
        python automate_Jose-Manurung.py
        echo "Pipeline preprocessing berhasil dieksekusi tanpa error!"
